export const PLANET_GET_DATA = "PLANET_GET_DATA";
export const PLANET_GET_DATA_SUCCESS = "PLANET_GET_DATA_SUCCESS";

export const CURRENT_PLANET_GET_DATA = "CURRENT_PLANET_GET_DATA";
export const CURRENT_PLANET_GET_DATA_SUCCESS =
  "CURRENT_PLANET_GET_DATA_SUCCESS";

export const FILMS_GET_DATA = "FILMS_GET_DATA";
export const FILMS_GET_DATA_SUCCCESS = "FILMS_GET_DATA_SUCCCESS";
